### PR TITLE
Migrate to Hugo #1

### LINKED ISSUE #1: Migrate to Hugo
To aid in further significant development, and ease community contribution, including translations, it is proposed that we transition this now hard-coded site to [Hugo](https://gohugo.io/) ~~([Syna](https://themes.gohugo.io/syna/) theme).~~

This should be done, given it's breadth, via a dedicated branch. Upon completion we then transition over and remove all hard coding to return again to leaveraging the advantages of a Static Site Generator. Prior now defunct/orphaned generator was thought to be [hyde](https://github.com/hyde/hyde).

Please update the Readme.md file while tending to this issue.

Ongoing progress/TODO list:

- [x] layouts/_default/single.html fails to make title wider (span12) than content (span8)- edit now center all page titles.
- [x] make feature summary icons link to specific feature on features browse page.
- [x] add links on downloads page to sha256 checksum files for all 8 non legacy downloads.
- [x] add Partners section - likely a partial displaying yet-another hugo [section](https://gohugo.io/content-management/sections/).
- [x] Banner pic, likely Pi4 and large dash montage/collage type thing. Likely we will drop carousel. 
- [x] migrate the problems/solutions content and formatting from old site.
- [x] Constrain feature list to the same width/container as the rest of the site.
- [x] add Alerts section - likely a partial and/or block. Used to flag server maintenance etc.
- [x] DIY installer section on downloads - possibly by way of a partial.
- [x] Possibly a testing rpm (versioned) zypper repo add section on downloads (for vanilla Leap installs).
- [x] Downloads page non constrained width wise.
- [x] Fix partner logos overlapping on narrow screen.
- [x] Add missing problem/solution section to custom solutions page. Important as that is a key area for us; given we are a DIY NAS setup.

### PR DESCRIPTION
**Pull request by phillxnet**
To aid in further significant development, and ease community contribution, including translations, transition away from our current hard-and-hand-coded / ex machine generated site to a custom themed Hugo setup.

Fixes #1 
@FroggyFlox I'm going to use this pr to test our in-development deployment back-end. But it is otherwise ready for review. However that will probably be easier once I've done the back-end bit. We can there after do some follow-up issues / pull requests to make the final config etc changes necessary for final production deployment. I.e. download production config elements etc.

Initially generated via "hugo new site --force ." and with an empty theme using Hugo v0.88.1+extended.

## Includes:
- Add .gitignore for Hugo and Pycharm.
- Abstract empty layout files from 'hugo new theme' mechanism.
- Move prior content of ./media/ (css, fonts, images, js) to ./static/.
- Move favicon from 'special' ./ico/ directory.
- Maintain existing html file stucture and maning (ugly url) as far as possible.
- Use hugo content sections for features, downloads, solutions, partners, and sysalerts.
- Use cascade _build in above sections where appropriate.
- Move EULA to full page format, with header and footer but maintain its final location.
- Use original FontAwesome github icon as no themify-icons yet.
- Use internal links whereever possible for performance reasons.
- Remove all 'wow' elements for performance and simplicity reasons.
- Remove some text duplication in Solutions front/page to the linked dedicated pages. This centralises each entry.
- Drop confusing resources page panel. This represented an unneeded navigation mechanism that was almost completely redundant.
- Add Tech Wiki entry, previously only found in resources, to top menu.
- Complete solutions Problem/Solution sections: previously] missing on custom page.
- Normalise download button away from 'button' to ease translation and improve look.
- Use several custom shortcodes to ease in-content formatting.
- Simplify formatting where ever possible.
- Drop front page carousell to aid in translation and keep things simple.
- Fix long standing 'invisible' links across a few pages.
- Drop subset of contributor pics as we link to GitHub where contirbutors can more easily control their 'appearance'.
- Add multi-email capability and move to linuxlines.com domain for support.
- Allow for multiple twitter accounts, old and new. With contextual awareness for those that should be 'featured' in the menu bar.
- Significantly enhance downloads page.
- Add sysalerts capability intended as a notification for system maintenance 'windows'.
- Add a features browse capability, or list view.
- Avoid using depricated Page.URL, to be removed in future versions of Hugo.
- Added custom 404.html layout and page content.
- Our prior download.html has become downloads.html. Not ideal but helps to keep things Hugo esk. I.e. default name for the section 'list'.
- Some initial multi-language capability has been installed.
- Add archetypes for all section content. Aids in new content type creation. Section pages inherit a page type of their section name.
- Remove redundant #contact sub menu entry that complicated the menu.
- Avoid using "-" in front matter parameters.
- Add single Taxonomy 'os' to aid in downloads section page os parameter abstraction.
- Add mechanism to list download / install options in preferred order.
- Fix 'Solutions' button by removing now redundant link col override.
- Add features list page menu item.
- Add image test (checksum) and transfer commands to download entries.
- Add rpm install instructions overview to downloads page.
- Add doc links to Downloads page for installer how-to and make usb.
- Update Readme with current website project status.
- Improve and update partners 'panel' on homepage.
- Remove graphical header from all but the homepage.
- Remove jquery.prettyPhoto.js and css.
- Remove html5shiv.js.
- Remove main.js - now redundant custom js.
- Remove older themed carousel images.
- Remove unused download source icons.
- Remove unused search icons.
- Remove unused glyphicons-halflings-regular font.
- Use built in .ExpiryDate (from front matter "expirydate") for alerts.
- Add dedicated DIY installer section on downloads page.
- Set api feature 'page' to draft state as we have no documentation for this and cannot currently field requests for such.
- Set new content, except sysalerts, to draft by default; via their respetive archetypes.
- Improve contribution, formatting, and testing advice to readme.

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox Merging and publishing soon there-after so we can move to getting things lined up ready for the re-release.

**Comment by phillxnet** [comment]
The product of this merge is now in production.

**Comment by FroggyFlox** [comment]
Thanks a lot, @phillxnet for yet another big project done!

**Comment by phillxnet** [comment]
@FroggyFlox Cheers, yes some what of a relief as it goes. Of course I've now noticed some more anomalies but at least we are now in Hugo land so easier to sort as we go along. I'll open new issues to address them individually. 

Fixes #21

**Comment by phillxnet** [comment]
Fixes #9

**Pull request merged**
